### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry for key 'visits_ip_visitable_id_visitable_type_date_unique'

### ISSUE THREAD

**Issue by notflip** [jordanmiguel/laravel-popular#14]
I've had a few errors in the last week where there's a duplicate entry from the ip address combined with the model name, for example `2a02:1810:9c07:c000:21e8:a1e4:9c43:26f4-45893-App\Models\NewsItem`

Any idea what might cause this? I didn't modify the migration that comes with the package

**Comment by notflip** [comment]
@jordanmiguel Do you have any idea how a duplicate key entry like this one above can occur?

**Comment by jordanmiguel** [comment]
@notflip I don't know, because the unique constraint is tied to the IP + date + visitable_type + visitable_id, and when we are going to register a visit, we use FirstOrCreate on this 4 fields, so, it should find it if it already exists, not try to re-add. Is this happening with frequency?

**Comment by notflip** [comment]
Thanks for getting back to me, it happened 68 times, around 12 times per day in the last 15 days. But what you say is correct, the firstOrCreate should have to catch it 🤔

**Comment by jordanmiguel** [comment]
@notflip it might have something to do with https://freek.dev/1087-breaking-laravels-firstorcreate-using-race-conditions, is this website a high traffic one?

**Comment by notflip** [comment]
It is a high traffic one! Thanks for the advice will check it out

**Comment by smayzes** [comment]
@jordanmiguel I get this on LaraChat.co and DevopsChat.co from time to time. I assume it happens when I have an influx of traffic.

**Comment by jyrkidn** [comment]
I found a fix for this based on this snippet: https://gist.github.com/RuGa/5354e44883c7651fd15c#file-massinsertorupdate-php.
If I add this code to my model, we don't get the errors anymore. It indeed has something to do with high traffic on the website.

```php
public function visit($ip = '')
{
    if (empty($ip)) {
        $ip = request()->ip();
    }

    return self::insertOrUpdateVisit([
        [
            'ip' => $ip,
            'date' => Carbon::now()->toDateString(),
            'visitable_id' => $this->id,
            'visitable_type' => (new \ReflectionClass($this))->getName(),
            'created_at' => now(),
            'updated_at' => now(),
        ]
    ]);
}

public static function insertOrUpdateVisit(array $rows)
{
    $table = 'visits';

    $first = reset($rows);

    $columns = implode(
        ',',
        array_map(function ($value) {
            return "$value";
        }, array_keys($first))
    );

    $values = implode(
        ',',
        array_map(function ($row) {
            return '(' . implode(
                ',',
                array_map(function ($value) {
                    return '"'.str_replace('"', '""', $value).'"';
                }, $row)
            ) . ')';
        }, $rows)
    );

    $updates = implode(
        ',',
        array_map(function ($value) {
            return "$value = VALUES($value)";
        }, array_keys($first))
    );

    $sql = "INSERT INTO {$table}({$columns}) VALUES {$values} ON DUPLICATE KEY UPDATE {$updates}";

    return DB::statement($sql);
}
```

**Comment by jordanmiguel** [comment]
@jyrkidn can you send a PR with the correction?

**Comment by jyrkidn** [comment]
Sorry it took me so long @jordanmiguel, but finally found some time for this: check https://github.com/jordanmiguel/laravel-popular/pull/19
