### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by sxilo-kek** [jordanmiguel/laravel-popular#3]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `visits` add unique `visits_ip_visitable_id_visitable_type_d
  ate_unique`(`ip`, `visitable_id`, `visitable_type`, `date`))

**Comment by jordanmiguel** [comment]
This is actually a MySQL issue, not related to the package.
